import type { ExpectedLine } from "./scoring";

/**
 * Regression tests you can run from the page.
 *
 * Every button in the demo is one of these: a scripted car with an expected cart
 * attached, played into the microphone bus and then scored. A judge sitting alone
 * at a laptop gets the same PASS/FAIL the offline bench produces, on the same audio,
 * without needing a second person or a working microphone.
 *
 * The clips are generated by `npm run clips` from the lines below, using AssemblyAI
 * voices, so the audio is identical on every machine.
 */

export type ScenarioCue =
  /** Once the agent has finished speaking, plus a beat. */
  | { kind: "after_agent"; delayMs?: number }
  /** A fixed moment after the scenario started — a voice that does not wait its turn. */
  | { kind: "at"; ms: number };

export type ScenarioStep = {
  /** Used for the clip filename: public/clips/<scenario>-<n>.wav */
  role: "driver" | "passenger" | "backseat" | "nextlane";
  voice: string;
  pitch?: number;
  gain?: number;
  text: string;
  cue: ScenarioCue;
};

export type Scenario = {
  id: string;
  title: string;
  proves: string;
  /** Engine rumble level while this scenario runs, 0–1. */
  engineNoise?: number;
  steps: ScenarioStep[];
  expect: {
    ticket: ExpectedLine[];
    mustNotContain?: string[];
    escalated?: boolean;
  };
};

const DRIVER = "george";
const PASSENGER = "mary";
const KID = "jane";
const LANE = "charles";

export const SCENARIOS: Scenario[] = [
  {
    id: "clean",
    title: "Plain order",
    proves: "the lane works before anything is made hard",
    steps: [
      {
        role: "driver",
        voice: DRIVER,
        text: "Can I get a double cheeseburger and a large fries.",
        cue: { kind: "after_agent", delayMs: 400 },
      },
      { role: "driver", voice: DRIVER, text: "That's everything, thanks.", cue: { kind: "after_agent", delayMs: 600 } },
    ],
    expect: {
      ticket: [
        { item: "Double Lab Burger", qty: 1, owner: "driver" },
        { item: "Fries", qty: 1, size: "large", owner: "driver" },
      ],
    },
  },
  {
    id: "backseat",
    title: "Kid shouts for a shake",
    proves: "a second voice never reaches the ticket on its own",
    engineNoise: 0.18,
    steps: [
      {
        role: "driver",
        voice: DRIVER,
        text: "I'll take a lab burger and a small coke.",
        cue: { kind: "after_agent", delayMs: 400 },
      },
      {
        role: "backseat",
        voice: KID,
        pitch: 1.22,
        gain: 0.85,
        text: "And a chocolate shake! I want a chocolate shake!",
        cue: { kind: "after_agent", delayMs: 300 },
      },
      {
        role: "driver",
        voice: DRIVER,
        text: "No, no shake. That's everything.",
        cue: { kind: "after_agent", delayMs: 500 },
      },
    ],
    expect: {
      ticket: [
        { item: "Lab Burger", qty: 1, owner: "driver" },
        { item: "Cola", qty: 1, size: "small", owner: "driver" },
      ],
      mustNotContain: ["Milkshake"],
    },
  },
  {
    id: "next-lane",
    title: "The next lane orders into our microphone",
    proves: "a voice that never spoke to this agent cannot put food on this ticket",
    engineNoise: 0.2,
    steps: [
      {
        role: "driver",
        voice: DRIVER,
        text: "Morning, I'd like a veggie lab, please.",
        cue: { kind: "after_agent", delayMs: 400 },
      },
      {
        role: "nextlane",
        voice: LANE,
        gain: 0.32,
        text: "Give me two large fries and an apple pie.",
        cue: { kind: "at", ms: 9000 },
      },
      {
        role: "driver",
        voice: DRIVER,
        text: "And that's everything for me.",
        cue: { kind: "after_agent", delayMs: 700 },
      },
    ],
    expect: {
      ticket: [{ item: "Veggie Lab", qty: 1, owner: "driver" }],
      mustNotContain: ["Fries", "Apple Pie"],
    },
  },
  {
    id: "hers",
    title: "Two burgers, one of them hers",
    proves: "a correction aimed at another person splits the line instead of changing both",
    engineNoise: 0.15,
    steps: [
      {
        role: "driver",
        voice: DRIVER,
        text: "Two lab burgers and a large fries.",
        cue: { kind: "after_agent", delayMs: 400 },
      },
      {
        role: "driver",
        voice: DRIVER,
        text: "Hers without pickles, just one of them.",
        cue: { kind: "after_agent", delayMs: 500 },
      },
      { role: "driver", voice: DRIVER, text: "That's everything.", cue: { kind: "after_agent", delayMs: 500 } },
    ],
    expect: {
      ticket: [
        { item: "Lab Burger", qty: 1, owner: "driver" },
        { item: "Lab Burger", qty: 1, modifiers: ["no pickles"] },
        { item: "Fries", qty: 1, size: "large", owner: "driver" },
      ],
    },
  },
  {
    id: "passenger",
    title: "Passenger orders for themselves",
    proves: "the held item is added on the driver's word and belongs to the passenger",
    engineNoise: 0.15,
    steps: [
      { role: "driver", voice: DRIVER, text: "A lab burger for me.", cue: { kind: "after_agent", delayMs: 400 } },
      {
        role: "passenger",
        voice: PASSENGER,
        gain: 0.9,
        text: "And a crispy chicken sandwich for me, please.",
        cue: { kind: "after_agent", delayMs: 400 },
      },
      {
        role: "driver",
        voice: DRIVER,
        text: "Yes, add her chicken sandwich. That's everything.",
        cue: { kind: "after_agent", delayMs: 400 },
      },
    ],
    expect: {
      ticket: [
        { item: "Lab Burger", qty: 1, owner: "driver" },
        { item: "Crispy Chicken Sandwich", qty: 1 },
      ],
    },
  },
  {
    id: "prank",
    title: "Two hundred and sixty nuggets",
    proves: "the order that ended a real drive-thru pilot never reaches the kitchen",
    steps: [
      {
        role: "driver",
        voice: DRIVER,
        text: "I want two hundred and sixty chicken nuggets.",
        cue: { kind: "after_agent", delayMs: 400 },
      },
    ],
    expect: { ticket: [], mustNotContain: ["Chicken Nuggets"], escalated: true },
  },
];

export const clipUrl = (scenarioId: string, index: number) => `/clips/${scenarioId}-${index}.wav`;
